<?php
/* LISTA DE PAISES*/
$tsPaises = [
	'AF' => 'Afganist&aacute;n',
	'AL' => 'Albania',
	'DE' => 'Alemania',
	'DZ' => 'Argelia',
	'AD' => 'Andorra',
	'AO' => 'Angola',
	'AI' => 'Anguila',
	'AG' => 'Antigua y Barbuda',
	'AQ' => 'Ant&aacute;rtida',
	'SA' => 'Arabia Saudita',
	'AR' => 'Argentina',
	'AM' => 'Armenia',
	'AW' => 'Aruba',
	'AU' => 'Australia',
	'AT' => 'Austria',
	'AZ' => 'Azerbaiy&aacute;n',
	'BS' => 'Bahamas',
	'BH' => 'Bahr&eacute;in',
	'BD' => 'Bangladesh',
	'BB' => 'Barbados',
	'BZ' => 'Belice',
	'BJ' => 'Benin',
	'BM' => 'Bermudas',
	'BY' => 'Bielorrusia',
	'BO' => 'Bolivia',
	'BA' => 'Bosnia y Herzegovina',
	'BW' => 'Botswana',
	'BR' => 'Brasil',
	'BN' => 'Brun&eacute;i',
	'BG' => 'Bulgaria',
	'BF' => 'Burkina Faso',
	'BI' => 'Burundi',
	'BT' => 'But&aacute;n',
	'BE' => 'B&eacute;lgica',
	'CV' => 'Cabo Verde',
	'KH' => 'Camboya',
	'CM' => 'Camer&uacute;n',
	'CA' => 'Canad&aacute;',
	'TD' => 'Chad',
	'CL' => 'Chile',
	'CN' => 'China',
	'CY' => 'Chipre',
	'VA' => 'Ciudad del Vaticano',
	'CO' => 'Colombia',
	'KM' => 'Comoras',
	'KP' => 'Corea del Norte',
	'KR' => 'Corea del Sur',
	'CR' => 'Costa Rica',
	'CI' => 'Costa de Marfil',
	'HR' => 'Croacia',
	'CU' => 'Cuba',
	'DK' => 'Dinamarca',
	'DM' => 'Dominica',
	'EC' => 'Ecuador',
	'EG' => 'Egipto',
	'SV' => 'El Salvador',
	'AE' => 'Emiratos &aacute;rabes Unidos',
	'ER' => 'Eritrea',
	'SK' => 'Eslovaquia',
	'SI' => 'Eslovenia',
	'ES' => 'Espa&ntilde;a',
	'US' => 'Estados Unidos',
	'EE' => 'Estonia',
	'ET' => 'Etiop&iacute;a',
	'PH' => 'Filipinas',
	'FI' => 'Finlandia',
	'FJ' => 'Fiyi',
	'FR' => 'Francia',
	'GA' => 'Gab&oacute;n',
	'GM' => 'Gambia',
	'GE' => 'Georgia',
	'GH' => 'Ghana',
	'GI' => 'Gibraltar',
	'GD' => 'Granada',
	'GR' => 'Grecia',
	'GL' => 'Groenlandia',
	'GP' => 'Guadalupe',
	'GU' => 'Guam',
	'GT' => 'Guatemala',
	'GF' => 'Guayana Francesa',
	'GG' => 'Guernsey',
	'GN' => 'Guinea',
	'GQ' => 'Guinea Ecuatorial',
	'GW' => 'Guinea-Bissau',
	'GY' => 'Guyana',
	'HT' => 'Hait&iacute;',
	'HN' => 'Honduras',
	'HK' => 'Hong Kong',
	'HU' => 'Hungr&iacute;a',
	'IN' => 'India',
	'ID' => 'Indonesia',
	'IQ' => 'Iraq',
	'IE' => 'Irlanda',
	'IR' => 'Ir&aacute;n',
	'BV' => 'Isla Bouvet',
	'IM' => 'Isla de Man',
	'CX' => 'Isla de Navidad',
	'IS' => 'Islandia',
	'KY' => 'Islas Caim&aacute;n',
	'CC' => 'Islas Cocos',
	'CK' => 'Islas Cook',
	'FO' => 'Islas Feroe',
	'GS' => 'Islas Georgias del Sur y Sandwich del Sur',
	'HM' => 'Islas Heard y McDonald',
	'MP' => 'Islas Marianas del Norte',
	'MH' => 'Islas Marshall',
	'PN' => 'Islas Pitcairn',
	'SB' => 'Islas Salom&oacute;n',
	'TC' => 'Islas Turcas y Caicos',
	'VG' => 'Islas V&iacute;rgenes Brit&aacute;nicas',
	'VI' => 'Islas V&iacute;rgenes Estadounidenses',
	'UM' => 'Islas ultramarinas de Estados Unidos',
	'IL' => 'Israel',
	'IT' => 'Italia',
	'JM' => 'Jamaica',
	'JP' => 'Jap&oacute;n',
	'JE' => 'Jersey',
	'JO' => 'Jordania',
	'KZ' => 'Kazajist&aacute;n',
	'KE' => 'Kenia',
	'KG' => 'Kirguist&aacute;n',
	'KI' => 'Kiribati',
	'KW' => 'Kuwait',
	'LA' => 'Laos',
	'LS' => 'Lesoto',
	'LV' => 'Letonia',
	'LR' => 'Liberia',
	'LY' => 'Libia',
	'LI' => 'Liechtenstein',
	'LT' => 'Lituania',
	'LU' => 'Luxemburgo',
	'LB' => 'L&iacute;bano',
	'MO' => 'Macao',
	'MG' => 'Madagascar',
	'MY' => 'Malasia',
	'MW' => 'Malaui',
	'MV' => 'Maldivas',
	'MT' => 'Malta',
	'ML' => 'Mal&iacute;',
	'MA' => 'Marruecos',
	'MQ' => 'Martinica',
	'MU' => 'Mauricio',
	'MR' => 'Mauritania',
	'YT' => 'Mayotte',
	'FM' => 'Micronesia',
	'MD' => 'Moldavia',
	'MN' => 'Mongolia',
	'ME' => 'Montenegro',
	'MS' => 'Montserrat',
	'MZ' => 'Mozambique',
	'MM' => 'Myanmar',
	'MX' => 'M&eacute;xico',
	'MC' => 'M&oacute;naco',
	'NA' => 'Namibia',
	'NR' => 'Nauru',
	'NP' => 'Nepal',
	'NI' => 'Nicaragua',
	'NE' => 'Niger',
	'NG' => 'Nigeria',
	'NU' => 'Niue',
	'NF' => 'Norfolk',
	'NO' => 'Noruega',
	'NC' => 'Nueva Caledonia',
	'NZ' => 'Nueva Zelanda',
	'OM' => 'Om&aacute;n',
	'PK' => 'Pakist&aacute;n',
	'PW' => 'Palaos',
	'PA' => 'Panam&aacute;',
	'PG' => 'Pap&uacute;a Nueva Guinea',
	'PY' => 'Paraguay',
	'NL' => 'Pa&iacute;ses Bajos',
	'PE' => 'Per&uacute;',
	'PF' => 'Polinesia Francesa',
	'PL' => 'Polonia',
	'PT' => 'Portugal',
	'PR' => 'Puerto Rico',
	'QA' => 'Qatar',
	'GB' => 'Reino Unido',
	'CF' => 'Rep&uacute;blica Centroafricana',
	'CZ' => 'Rep&uacute;blica Checa',
	'CD' => 'Rep&uacute;blica Democr&aacute;tica del Congo',
	'DO' => 'Rep&uacute;blica Dominicana',
	'MK' => 'Rep&uacute;blica de Macedonia',
	'CG' => 'Rep&uacute;blica del Congo',
	'EH' => 'Rep&uacute;blica &aacute;rabe Saharaui Democr&aacute;tica',
	'RE' => 'Reuni&oacute;n',
	'RW' => 'Ruanda',
	'RO' => 'Rumania',
	'RU' => 'Rusia',
	'MF' => 'Saint-Martin',
	'WS' => 'Samoa',
	'AS' => 'Samoa Americana',
	'BL' => 'San Bartolom&eacute;',
	'KN' => 'San Crist&oacute;bal y Nieves',
	'SM' => 'San Marino',
	'PM' => 'San Pedro y Miquel&oacute;n',
	'VC' => 'San Vicente y las Granadinas',
	'SH' => 'Santa Helena',
	'LC' => 'Santa Luc&iacute;a',
	'ST' => 'Sao Tom&eacute; y Principe',
	'SN' => 'Senegal',
	'RS' => 'Serbia',
	'SC' => 'Seychelles',
	'SL' => 'Sierra Leona',
	'SG' => 'Singapur',
	'SY' => 'Siria',
	'SO' => 'Somalia',
	'LK' => 'Sri Lanka',
	'SZ' => 'Suazilandia',
	'ZA' => 'Sud&aacute;frica',
	'SD' => 'Sud&aacute;n',
	'SE' => 'Suecia',
	'CH' => 'Suiza',
	'SR' => 'Surinam',
	'SJ' => 'Svalbard y Jan Mayen',
	'TH' => 'Tailandia',
	'TW' => 'Taiw&aacute;n',
	'TZ' => 'Tanzania',
	'TJ' => 'Tayikist&aacute;n',
	'IO' => 'Territorio Brit&aacute;nico del Oc&eacute;ano &iacute;ndico',
	'TF' => 'Territorios Australes Franceses',
	'PS' => 'Territorios palestinos',
	'TL' => 'Timor Oriental',
	'TG' => 'Togo',
	'TK' => 'Tokelau',
	'TO' => 'Tonga',
	'TT' => 'Trinidad y Tobago',
	'TM' => 'Turkmenist&aacute;n',
	'TR' => 'Turqu&iacute;a',
	'TV' => 'Tuvalu',
	'TN' => 'T&uacute;nez',
	'UA' => 'Ucrania',
	'UG' => 'Uganda',
	'UY' => 'Uruguay',
	'UZ' => 'Uzbekist&aacute;n',
	'VU' => 'Vanuatu',
	'VE' => 'Venezuela',
	'VN' => 'Vietnam',
	'WF' => 'Wallis y Futuna',
	'YE' => 'Yemen',
	'DJ' => 'Yibuti',
	'ZM' => 'Zambia',
	'ZW' => 'Zimbabue'
];	
// MESES
$tsMeses = [
	1 => 'Enero',
	2 => 'Febrero',
	3 => 'Marzo',
	4 => 'Abril',
	5 => 'Mayo',
	6 => 'Junio',
	7 => 'Julio',
	8 => 'Agosto',
	9 => 'Septiembre',
	10 => 'Octubre',
	11 => 'Noviembre',
	12 => 'Diciembre',
];
/*********** PERFIL *******************/
$tsPerfilData = [
	/* ESTADO CIVIL */
	'estado' => [
		'Sin Respuesta',
		'Soltero/a',
		'Con novio/a',
		'Casado/a',
		'Divorciado/a',
		'Viudo/a',
		'En algo...'
	]
];
// PRIVACIDAD
$tsPrivacidad = [
	'Nadie',
	'Usuarios que sigo y me siguen',
	'Usuarios que sigo o me siguen',
	'Mis seguidores',
	'Usuarios que sigo',
	'Usuarios registrados',
	'Todos'
];
/* DENUNCIAS */
$tsDenuncias = [
	'users' => [
		'',
		'Perfil falso/clon',
		'Usuario insultante y agresivo',
		'Publicaciones inapropiadas',
		'Foto del perfil inapropiada',
		'Publicidad no deseada (SPAM]',
	],
	'posts' => [
		'',
		'Re-post',
		'Se hace Spam',
		'Tiene links muertos',
		'Es racista o irrespetuoso',
		'Contiene informaci&oacute;n personal',
		'El t&iacute;tulo esta en may&uacute;scula',
		'Contiene pedofilia',
		'Es gore o asqueroso',
		'Est&aacute; mal la fuente',
		'Post demasiado pobre / Crap',
		$tsCore->settings['titulo'].' no es un foro',
		'No cumple con el protocolo',
		'Otra raz&oacute;n (especificar]'
	],
	'fotos' => [
		'',
		'Ya est&aacute; publicada',
		'Se hace Spam',
		'La imagen est&aacute; ca&iacute;da',
		'Es racista o irrespetuosa',
		'Contiene informaci&oacute;n personal',
		'Contiene pedofilia',
		'Es gore o asquerosa',
		'Otra raz&oacute;n (especificar]'
	],
	'files' => [
		'',
		'Ya est&aacute; publicada',
		'Contenido malicioso',
		'Contenido obseno',
		'Es racista o irrespetuosa',
		'Contiene informaci&oacute;n personal',
		'Contiene pedofilia',
		'Es gore o asquerosa',
		'Otra raz&oacute;n (especificar]'
	]
];
/* TIPOS DE ARCHIVOS */
$tsExt = [
	// Con esto quiere decir que podemos mostrar el archivo
	'allow' => [
		'3gp', 
		'avi', 
		'bat',
		'bmp', 
		'css', 
		'flv', 
		'gif', 
		'html', 
		'jpeg', 
		'jpg', 
		'js', 
		'json', 
		'less',
		'mkv', 
		'mp3', 
		'mp4', 
		'mpeg', 
		'mpg', 
		'ogg', 
		'ogg', 
		'pdf', 
		'png', 
		'sass',
		'svg',
		'swf', 
		'txt', 
		'wav', 
		'webm', 
		'webp', 
		'wmv'
	],
	// Podemos ver las imagenes
	'images' => [
		'bmp',
		'gif',
		'jpg',
		'png',
		'svg',
		'webp'
	],
	// Podemos verlo en un textarea
	'text' => [
		'bat',
		'css',
		'html',
		'js',
		'json',
		'less',
		'sass',
		'txt'
	],
	// Podemos ver los videos
	'videos' => [
		'3gp',
		'avi', 
		'flv', 
		'mkv', 
		'mpg', 
		'wmv'
	],
	'mime-video' => [
		'3gp' => '3gpp',
		'avi' => 'x-msvideo',
		'flv' => 'x-flv', 
		'mkv' => 'x-matroska', 
		'mp4' => 'mp4', 
		'mpg' => 'mpeg', 
		'wmv' => 'x-ms-wmv'
	]
];
/**
  * Si van a agregar más debe ser así 'nombre_minuscula => 'nombre_inicial_mayuscula',
*/
$redes = [
	'facebook' => [
		'iconify' => 'la:facebook-f',
		'nombre' => 'Facebook', 
		'url' => 'https://facebook.com'
	],
	'twitter' => [
		'iconify' => 'pajamas:twitter',
		'nombre' => 'Twitter', 
		'url' => 'https://twitter.com'
	],
	'instagram' => [
		'iconify' => 'la:instagram',
		'nombre' => 'Instagram',
		'url' => 'https://twitter.com'
	],
	'youtube' => [
		'iconify' => 'la:youtube',
		'nombre' => 'Youtube',
		'url' => 'https://youtube.com'
	],
	'twitch' => [
		'iconify' => 'la:twitch',
		'nombre' => 'Twitch',
		'url' => 'https://twitch.tv'
	],
	'tiktok' => [
		'iconify' => 'logos:tiktok-icon',
		'nombre' => 'Tiktok',
		'url' => 'https://www.tiktok.com/@'
	],
	'discord' => [
		'iconify' => 'la:discord',
		'nombre' => 'Discord',
		'url' => 'https://discord.com/users'
	],
	'reddit' => [
		'iconify' => 'la:reddit-alien',
		'nombre' => 'Reddit',
		'url' => 'https://www.reddit.com/user'
	]
];